fireflyprotocol/bluefin-v2-client-ts

package.json, src/bluefinClient.ts
- Added a helper function for generating onboarding signature
- use that helper function also in init() function
=> Add helper for Onboarding signature

package.json, public/src/examples/1.initialisation.ts, public/src/examples/13.readonly_initialisation.ts, src/bluefinClient.ts, yarn.lock
- Currently depositToMarginBank tries to get USDC coin having enough balance that a user is trying to deposit.
- In case of no such coin containing enough balance , the call throws error.
- We need to merge coins for user if the amount to be deposited can not be covered by a single coin.
=> [EXC-1783] Add Coin Merging In Deposit

package.json, yarn.lock
=> Bump up library sui

package.json, src/constants.ts
=> Add config for devnet

package.json, src/bluefinClient.ts, src/exchange/contractService.ts, src/interfaces/routes.ts, yarn.lock
- Updated Adjust Leverage Call to be from Dapi for UI clients
- Updated Sponsored call to be via dapi for Adjust Leverage
=> [EXC-2621] Update Adjust Leverage Call To Make Dapi Call For UI Clients

package.json, yarn.lock
* Part of mitigation for incident-287
=> Bumping version of library-sui

package.json, src/bluefinClient.ts, src/exchange/interactorService.ts, yarn.lock
- This PR would be merged after the contracts upgrades is taken out on production. 
- Bumped library sui have updated the contract calls to include SUI CLOCK time in params
=> [EXC-2684] Bump Library Sui For Upgraded Contracts Calls

package.json, yarn.lock
=> updated lib sui

package.json, yarn.lock
=> chore: bump library-sui version

package.json, yarn.lock
=> bump lib version

package.json, yarn.lock
=> Fix zklogin for swap - bump sui lib

package.json, yarn.lock
=> chore: upgrade library-sui version to 2.3.3

.github/workflows/publish_prerelease.yml, package.json, yarn.lock
=> Bump library version for zk login support

package.json, yarn.lock
=> chore: bump library-sui to version 2.4.2

package.json
=> chore: fix package version

package.json, yarn.lock
=> chore: update lib sui

package.json
=> fix: version conflict fix

package.json, src/bluefinClient.ts, yarn.lock
=> Added logs for onboarding flow

package.json, src/bluefinClient.ts
=> Sponsortx check

package.json, src/bluefinClient.ts, src/constants.ts, src/exchange/apiUrls.ts, src/interfaces/routes.ts, tests/bluefinClient.test.ts
- Added offchain settlement updates route and tests
=> [BLB-223] Added offchain settlement updates route

package.json, src/bluefinClient.ts, src/exchange/apiService.ts
- Added onboarding url in the auth headers
=> [BLB-258] Added onboarding url in the auth headers

package.json, yarn.lock
=> feat[BFS-669]: use latest library-sui to support RFQ

package.json, proDeployment.json, spotDeployment.json, src/bluefinClient.ts, src/exchange/contractErrorHandling.service.ts, src/exchange/contractService.ts, utils/utils.ts, yarn.lock
- PTB calls for closeAndWithdraw, swapAndDeposit, withdrawSwapAndDeposit, closeWithdrawSwapAndDeposit
=> [BLB-650] PTB calls for closeAndWithdraw, swapAndDeposit

package.json, src/bluefinClient.ts, src/exchange/apiUrls.ts
- added endpoint in client to check the user has AV.
=> feat(BLB-677): added endpoint in client to check the user has AV.

package.json, src/bluefinClient.ts, src/exchange/contractErrorHandling.service.ts, yarn.lock
- Updated success messages of ptb calls
=> Updated success messages

package.json, src/bluefinClient.ts, src/exchange/contractErrorHandling.service.ts, src/exchange/contractService.ts, utils/utils.ts
- Handle deposit error and make PTB work on active markets
=> [BLB-689] Handle deposit error and make PTB work on active markets

package.json, src/bluefinClient.ts, src/exchange/contractService.ts, yarn.lock
7k estimation method for withdrawl amount with delisted position
=> [BLB-691] 7k estimation method for withdrawl amount with delisted position
